version: '3.8'

services:
  tut_factory:
    container_name: tut-factory-container
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/usr/tut-factory
    env_file: .env.db.dev
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
      - '5000:5000'
    tty: true
    stdin_open: true
    depends_on:
      tut_factory_db:
        condition: service_healthy
        restart: true

  tut_factory_db:
    container_name: tut-factory-db-container
    image: mysql:8.1.0
    restart: always
    env_file: .env.db.dev
    ports:
      - '3306:3306'
    volumes:
      - tut_factory_db_mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3306']
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 2s

volumes:
  tut_factory_db_mysql:
