name: shell commands 

on: "push"

jobs:
  hello-world:
    runs-on: ubuntu-22.04
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: multiline script
        run: |
          node -v
          npm -v